# Generated by Django 2.1 on 2018-08-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='guessed_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess_date', models.DateTimeField()),
                ('breed', models.CharField(max_length=50)),
                ('accurancy', models.CharField(max_length=4)),
                ('correct', models.BooleanField(default=False)),
            ],
        ),
    ]
